# Dockerfile para la Ingesta de Telemetría
# Deberá contener:
# - Imagen de Python (ej. python:3.11-slim)
# - Instalación de dependencias (websockets, kafka-python, pydantic)
# - Comando de arranque del script productor (CMD ["python", "src/producer.py"])
